use_frameworks!

target 'PicStamp_Example' do
  pod 'PicStamp', :path => '../'

  target 'PicStamp_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
